exports.ChanelName = {
	hall: "hall" //大厅
};
exports.pushCmd = {
	chat: 'chat',
	voice: 'voice',
	quit: 'quit',
	closeGame: 'closeGame',
	serverLeave: 'serverLeave', //服务器端离线，广播全体
	laba: 'laba',
	game: 'game',
	roomCardsChange: 'roomCardsChange',
	serverReboot: 'serverReboot',
	updateClient: 'updateClient',
	ticketChange:'ticketChange',
	level:'level',
	vipLevel:'vipLevel',
	expsAll:'expsAll',
	vip_rounds:'vip_rounds',
	prop:'prop',
	packet_award:'packet_award',
	emoji:'emoji',
	matchresult:'matchresult',
	matchConfirm:'matchConfirm',
	stonesChange:'stonesChange',
	openroom:'openroom',
	enterroom:'enterroom',
	matchticket:'matchticket',
	familyChange:'familyChange',
	acpayResult:'acpayResult',
	changeGolds: 'changeGolds'
};

//游戏进入状态
exports.RoomEnterState = {
	ENTER_OK: 0,
	ENTER_WRONG_INGAME: 1, //游戏中
	ENTER_WRONG_RELOAD: 2, //需要重新load
	ENTER_WRONG_CHANNEL: 3, //请求的频道不对
	ENTER_WRONG_GOLDS: 4, //玩家金币不符合要求
	ENTER_WRONG_ACCOUNT: 5, //帐号异常，禁止登陆
	ENTER_WRONG_OTHERLOGIN: 6, //帐号在别处上线
	ENTER_WRONG_ROOMFULL: 7, //房间已满
	ENTER_WRONG_OTHERGAME: 8, //在另外的游戏中
	ENTER_WRONG_NULLPOP: 9, //连续15把不下注，或者携带筹码小于最底倍连续5把不下注；踢回大厅
	ENTER_WRONG_GOLDS_LITTLE: 10, //玩家金币不符合要求，太少
	ENTER_WRONG_GOLDS_MUCH: 11, //玩家金币不符合要求，太多
	ENTER_WRONG_TABLE_VIP: 12 //桌子VIP
};

CMD = {};
CMD.OGID_MSGBASE_CONTROLBASE = 0x2500;

CMD.REQ = 0;
CMD.ACK = 0x8000000;
exports.CMD = CMD;

var cmdsorts = {};

exports.debugCmdInfo = function(cmdid, gid) {
	gid = gid || '';
	for (var cmd in CMD) {
		var cmdv = CMD[cmd];
		if (cmdv == cmdid) {
			return cmdsorts[cmdv];
		} else if ((cmdv | CMD.ACK) == cmdid) {
			return cmdsorts[cmdv] + "|CMD.ACK";
		} else if ((cmdv | CMD.REQ) == cmdid) {
			return cmdsorts[cmdv] + "|CMD.REG";
		}
	}
	return "未知命令 " + cmdid + ' ' + gid + ' ' + (cmdid - (cmdid > CMD.ACK ? CMD.ACK : CMD.REQ));
};

//控制通信类型
CMD.OGID_MSGBASE_CONTROLBASE=0x2500; cmdsorts[CMD.OGID_MSGBASE_CONTROLBASE] = "CMD.OGID_MSGBASE_CONTROLBASE"; //9472
CMD.OGID_CONTROL_REGIS = (CMD.OGID_MSGBASE_CONTROLBASE + 0); cmdsorts[CMD.OGID_CONTROL_REGIS] = " 注册 CMD.OGID_CONTROL_REGIS"; //9472 注册
CMD.OGID_CONTROL_USER = (CMD.OGID_MSGBASE_CONTROLBASE + 1); cmdsorts[CMD.OGID_CONTROL_USER] = " 查看玩家游戏信息 CMD.OGID_CONTROL_USER"; //9473 查看玩家游戏信息
CMD.OGID_CONTROL_GAME_STATE = (CMD.OGID_MSGBASE_CONTROLBASE + 2); cmdsorts[CMD.OGID_CONTROL_GAME_STATE] = " 游戏状态信息 CMD.OGID_CONTROL_GAME_STATE"; //9474 游戏状态信息
CMD.OGID_CONTROL_GATE = (CMD.OGID_MSGBASE_CONTROLBASE + 3); cmdsorts[CMD.OGID_CONTROL_GATE] = " 控制门 CMD.OGID_CONTROL_GATE"; //9475 控制门
CMD.OGID_CONTROL_RUSERS = (CMD.OGID_MSGBASE_CONTROLBASE + 4); cmdsorts[CMD.OGID_CONTROL_RUSERS] = " 获得房间内的玩家信息 CMD.OGID_CONTROL_RUSERS"; //9476 获得房间内的玩家信息
CMD.OGID_CONTROL_USER_GOLDS = (CMD.OGID_MSGBASE_CONTROLBASE + 5); cmdsorts[CMD.OGID_CONTROL_USER_GOLDS] = " 玩家金币改变 CMD.OGID_CONTROL_USER_GOLDS"; //9477 玩家金币改变
CMD.OGID_CONTROL_KICK_USER = (CMD.OGID_MSGBASE_CONTROLBASE + 6); cmdsorts[CMD.OGID_CONTROL_KICK_USER] = "控制踢人 CMD.OGID_CONTROL_KICK_USER"; //9478 控制踢人
CMD.OGID_CONTROL_JOB_TABLE = (CMD.OGID_MSGBASE_CONTROLBASE + 7); cmdsorts[CMD.OGID_CONTROL_JOB_TABLE] = " 关于包桌:type:0,包桌;1,取消包桌;2,取钱;3,加钱;4,押金变化 CMD.OGID_CONTROL_JOB_TABLE"; //9479 关于包桌:type:0,包桌;1,取消包桌;2,取钱;3,加钱
CMD.OGID_CONTROL_ADD_GOLDS = (CMD.OGID_MSGBASE_CONTROLBASE + 8); cmdsorts[CMD.OGID_CONTROL_ADD_GOLDS] = " 通知玩家加金币 CMD.OGID_CONTROL_ADD_GOLDS"; //9480 通知玩家加金币
CMD.OGID_CONTROL_MSG = (CMD.OGID_MSGBASE_CONTROLBASE + 9); cmdsorts[CMD.OGID_CONTROL_MSG] = " 通用消息 CMD.OGID_CONTROL_MSG"; //9481 通知玩家加金币
CMD.OGID_CONTROL_TABLE_RECORD = (CMD.OGID_MSGBASE_CONTROLBASE + 10); cmdsorts[CMD.OGID_CONTROL_TABLE_RECORD] = " 路子 CMD.OGID_CONTROL_TABLE_RECORD"; //9482 路子
CMD.OGID_CONTROL_BONUS_GOLDS = (CMD.OGID_MSGBASE_CONTROLBASE + 11); cmdsorts[CMD.OGID_CONTROL_BONUS_GOLDS] = " 玩家bonus_golds合并到golds CMD.OGID_CONTROL_BONUS_GOLDS"; //9483 玩家bonus_golds合并到golds
CMD.OGID_CONTROL_TABLE_CONTROL = (CMD.OGID_MSGBASE_CONTROLBASE + 12); cmdsorts[CMD.OGID_CONTROL_TABLE_CONTROL] = "控制指令 CMD.OGID_CONTROL_TABLE_CONTROL"; //9484 玩家bonus_golds合并到golds
CMD.OGID_CONTROL_HEART_BEAT = (CMD.OGID_MSGBASE_CONTROLBASE + 13); cmdsorts[CMD.OGID_CONTROL_HEART_BEAT] = "心跳 CMD.OGID_CONTROL_HEART_BEAT"; //9485 心跳
CMD.OGID_CONTROL_MOTOR_SIGN = (CMD.OGID_MSGBASE_CONTROLBASE + 14); cmdsorts[CMD.OGID_CONTROL_MOTOR_SIGN] = "比赛机器人报名 CMD.OGID_CONTROL_MOTOR_SIGN"; //9486 比赛机器人报名
CMD.OGID_CONTROL_USER_RANKING = (CMD.OGID_MSGBASE_CONTROLBASE + 15); cmdsorts[CMD.OGID_CONTROL_USER_RANKING] = "本局游戏输赢排名 CMD.OGID_CONTROL_USER_RANKING"; //9487 本局游戏输赢排名
CMD.OGID_CONTROL_GAME_END = (CMD.OGID_MSGBASE_CONTROLBASE + 16); cmdsorts[CMD.OGID_CONTROL_GAME_END] = "本局游戏结束 CMD.OGID_CONTROL_GAME_END"; //9488 本局游戏结束
CMD.OGID_CONTROL_MATCH_USER_RISE = (CMD.OGID_MSGBASE_CONTROLBASE + 18); cmdsorts[CMD.OGID_CONTROL_MATCH_USER_RISE] = "MTT比赛开始 CMD.OGID_CONTROL_MATCH_USER_RISE"; //9490 天梯赛复活

CMD.OGID_CONTROL_MATCH_RANK = (CMD.OGID_MSGBASE_CONTROLBASE + 22); cmdsorts[CMD.OGID_CONTROL_MATCH_RANK] = "MTT比赛开始 CMD.OGID_CONTROL_MATCH_RANK"; //9494 比赛结果
CMD.OGID_CONTROL_MATCH_COMMON_INFO = (CMD.OGID_MSGBASE_CONTROLBASE + 23); cmdsorts[CMD.OGID_CONTROL_MATCH_COMMON_INFO] = "MTT比赛开始 CMD.OGID_CONTROL_MATCH_COMMON_INFO"; //9495 比赛通用消息

CMD.OGID_CONTROL_TABLE_LIST = (CMD.OGID_MSGBASE_CONTROLBASE + 101); cmdsorts[CMD.OGID_CONTROL_TABLE_LIST] = "控制指令 CMD.OGID_CONTROL_TABLE_LIST"; //9484 玩家bonus_golds合并到golds

CMD.OGID_CONTROL_ONCREATE_TABLE = (CMD.OGID_MSGBASE_CONTROLBASE + 28); cmdsorts[CMD.OGID_CONTROL_ONCREATE_TABLE] = "创建桌子 CMD.OGID_CONTROL_ONCREATE_TABLE"; //9500
CMD.OGID_CONTROL_CANCEL_TABLE = (CMD.OGID_MSGBASE_CONTROLBASE + 29); cmdsorts[CMD.OGID_CONTROL_CANCEL_TABLE] = "解散桌子 CMD.OGID_CONTROL_CANCEL_TABLE"; //9501 解散桌子
CMD.OGID_CONTROL_MATCH_USER_SIGN = (CMD.OGID_MSGBASE_CONTROLBASE + 30); cmdsorts[CMD.OGID_CONTROL_MATCH_USER_SIGN] = "比赛玩家报名/取消报名 CMD.OGID_CONTROL_MATCH_USER_SIGN"; //9502 比赛玩家报名/取消报名
CMD.OGID_CONTROL_MATCH_DISTRIBUTE_USER = (CMD.OGID_MSGBASE_CONTROLBASE + 31); cmdsorts[CMD.OGID_CONTROL_MATCH_DISTRIBUTE_USER] = "比赛玩家报名/取消报名 CMD.OGID_CONTROL_MATCH_DISTRIBUTE_USER"; //9503 玩家分桌

CMD.OGID_CONTROL_MATCH_START_END = (CMD.OGID_MSGBASE_CONTROLBASE + 34); cmdsorts[CMD.OGID_CONTROL_MATCH_START_END] = "比赛 CMD.OGID_CONTROL_MATCH_START_END"; //9506 比赛开始
CMD.OGID_CONTROL_USER_TUIKA = (CMD.OGID_MSGBASE_CONTROLBASE + 35); cmdsorts[CMD.OGID_CONTROL_USER_TUIKA] = "离开退卡 CMD.OGID_CONTROL_USER_TUIKA"; //9507 离开

CMD.OGID_CONTROL_MATCH_LAST_ENDROUND = (CMD.OGID_MSGBASE_CONTROLBASE + 37); cmdsorts[CMD.OGID_CONTROL_MATCH_LAST_ENDROUND] = "离开退卡 CMD.OGID_CONTROL_MATCH_LAST_ENDROUND"; //9509 比赛阶段结算

CMD.OGID_CONTROL_SLOTS_INTO = (CMD.OGID_MSGBASE_CONTROLBASE + 146); cmdsorts[CMD.OGID_CONTROL_SLOTS_INTO] = "监控信息 CMD.OGID_CONTROL_SLOTS_INTO"; //9618 监控信息

//任务通信类型
CMD.OGID_MSGBASE_TASKBASE=0x2800; cmdsorts[CMD.OGID_MSGBASE_TASKBASE] = "CMD.OGID_MSGBASE_TASKBASE"; //10240
CMD.OGID_TASKSERVER_LOGIN = (CMD.OGID_MSGBASE_TASKBASE + 0); cmdsorts[CMD.OGID_TASKSERVER_LOGIN] = " 登录 CMD.OGID_TASKSERVER_LOGIN"; //10240 登录
CMD.OGID_TASKSERVER_TASK = (CMD.OGID_MSGBASE_TASKBASE + 1); cmdsorts[CMD.OGID_TASKSERVER_TASK] = " 发送任务 CMD.OGID_TASKSERVER_TASK"; //10241 发送任务
CMD.OGID_TASKSERVER_CHAT = (CMD.OGID_MSGBASE_TASKBASE + 2); cmdsorts[CMD.OGID_TASKSERVER_CHAT] = " 聊天 CMD.OGID_TASKSERVER_CHAT"; //10242 聊天
CMD.OGID_TASKSERVER_TASK_DATA = (CMD.OGID_MSGBASE_TASKBASE + 3); cmdsorts[CMD.OGID_TASKSERVER_TASK_DATA] = " 更新任务数据 CMD.OGID_TASKSERVER_TASK_DATA"; //10243 更新任务数据
CMD.OGID_TASKSERVER_TASK_BONUS = (CMD.OGID_MSGBASE_TASKBASE + 4); cmdsorts[CMD.OGID_TASKSERVER_TASK_BONUS] = " 领取任务奖励 CMD.OGID_TASKSERVER_TASK_BONUS"; //10244 领取任务奖励
CMD.OGID_TASKSERVER_ONLINE = (CMD.OGID_MSGBASE_TASKBASE + 5); cmdsorts[CMD.OGID_TASKSERVER_ONLINE] = " 在线列表 CMD.OGID_TASKSERVER_ONLINE"; //10245 在线列表
CMD.OGID_TASKSERVER_MSG = (CMD.OGID_MSGBASE_TASKBASE + 6); cmdsorts[CMD.OGID_TASKSERVER_MSG] = " 消息:type=0,login;1,logout;2,login table;3,logout table CMD.OGID_TASKSERVER_MSG"; //10246 消息:type=0,login;1,logout;2,login table;3,logout table
CMD.OGID_TASKSERVER_LABA = (CMD.OGID_MSGBASE_TASKBASE + 7); cmdsorts[CMD.OGID_TASKSERVER_LABA] = " 大喇叭 shane|msg CMD.OGID_TASKSERVER_LABA"; //10247 大喇叭 shane|msg
CMD.OGID_TASKSERVER_CLIENTB = (CMD.OGID_MSGBASE_TASKBASE + 8); cmdsorts[CMD.OGID_TASKSERVER_CLIENTB] = " 客户端触发完成任务 CMD.OGID_TASKSERVER_CLIENTB"; //10248 客户端触发完成任务
CMD.OGID_TASKSERVER_ROOM_USERS = (CMD.OGID_MSGBASE_TASKBASE + 9); cmdsorts[CMD.OGID_TASKSERVER_ROOM_USERS] = " 获取每个房间的玩家个数 CMD.OGID_TASKSERVER_ROOM_USERS"; //10249 获取每个房间的玩家个数
CMD.OGID_TASKSERVER_ROOM_TABLES = (CMD.OGID_MSGBASE_TASKBASE + 10); cmdsorts[CMD.OGID_TASKSERVER_ROOM_TABLES] = " 获取房间内的桌子信息 CMD.OGID_TASKSERVER_ROOM_TABLES"; //10250 获取房间内的桌子信息
CMD.OGID_TASKSERVER_TABLE_INFO = (CMD.OGID_MSGBASE_TASKBASE + 11); cmdsorts[CMD.OGID_TASKSERVER_TABLE_INFO] = " 获取桌子信息 CMD.OGID_TASKSERVER_TABLE_INFO"; //10251 获取桌子信息
CMD.OGID_TASKSERVER_USER_INOUT = (CMD.OGID_MSGBASE_TASKBASE + 12); cmdsorts[CMD.OGID_TASKSERVER_USER_INOUT] = " 玩家进出 CMD.OGID_TASKSERVER_USER_INOUT"; //10252 玩家进出

//定义二人麻将的通信类型
CMD.OGID_MSGBASE_ROOMMSGBASE=0x3200; cmdsorts[CMD.OGID_MSGBASE_ROOMMSGBASE] = "CMD.OGID_MSGBASE_ROOMMSGBASE";
CMD.OGID_ROOMSVR_LOGIN = (CMD.OGID_MSGBASE_ROOMMSGBASE + 0); cmdsorts[CMD.OGID_ROOMSVR_LOGIN] = "x3200 登录 CMD.OGID_ROOMSVR_LOGIN"; //0x3200 登录
CMD.OGID_ROOMSVR_ENTERROOM = (CMD.OGID_MSGBASE_ROOMMSGBASE + 1); cmdsorts[CMD.OGID_ROOMSVR_ENTERROOM] = " 进入房间 CMD.OGID_ROOMSVR_ENTERROOM"; //12801 进入房间
//CMD.OGID_ROOMSVR_STARTGAME = (CMD.OGID_MSGBASE_ROOMMSGBASE + 2); cmdsorts[CMD.OGID_ROOMSVR_STARTGAME] = " CMD.OGID_ROOMSVR_STARTGAME"; //12802
CMD.OGID_ROOMSVR_BC = (CMD.OGID_MSGBASE_ROOMMSGBASE + 3); cmdsorts[CMD.OGID_ROOMSVR_BC] = " CMD.OGID_ROOMSVR_BC"; //12803
//CMD.OGID_ROOMSVR_IDLE = (CMD.OGID_MSGBASE_ROOMMSGBASE + 4); cmdsorts[CMD.OGID_ROOMSVR_IDLE] = " CMD.OGID_ROOMSVR_IDLE"; //12804
CMD.GLID_MAHJONG_PLACE = (CMD.OGID_MSGBASE_ROOMMSGBASE + 5); cmdsorts[CMD.GLID_MAHJONG_PLACE] = " CMD.GLID_MAHJONG_PLACE 开始游戏"; //12805 开始游戏
CMD.GLID_MAHJONG_OPRATION = (CMD.OGID_MSGBASE_ROOMMSGBASE + 6); cmdsorts[CMD.GLID_MAHJONG_OPRATION] = " CMD.GLID_MAHJONG_OPRATION 发送玩家的操作"; //12806 发送玩家的操作
CMD.OGID_ROOMSVR_GETCANENTERCHANNELS = (CMD.OGID_MSGBASE_ROOMMSGBASE + 7); cmdsorts[CMD.OGID_ROOMSVR_GETCANENTERCHANNELS] = " CMD.OGID_ROOMSVR_GETCANENTERCHANNELS"; //12807
CMD.GLID_MAHJONG_MJCARD = (CMD.OGID_MSGBASE_ROOMMSGBASE + 8); cmdsorts[CMD.GLID_MAHJONG_MJCARD] = " CMD.GLID_MAHJONG_MJCARD 发送玩家牌信息"; //12808 发送玩家牌信息

CMD.GLID_MAHJONG_OPERATION_PENG = (CMD.OGID_MSGBASE_ROOMMSGBASE + 9); cmdsorts[CMD.GLID_MAHJONG_OPERATION_PENG] = " CMD.GLID_MAHJONG_OPERATION_PENG 碰"; //12809 碰
CMD.GLID_MAHJONG_OPERATION_GANG = (CMD.OGID_MSGBASE_ROOMMSGBASE + 10); cmdsorts[CMD.GLID_MAHJONG_OPERATION_GANG] = " CMD.GLID_MAHJONG_OPERATION_GANG 杠"; //12810 杠
CMD.GLID_MAHJONG_OPERATION_POP = (CMD.OGID_MSGBASE_ROOMMSGBASE + 11); cmdsorts[CMD.GLID_MAHJONG_OPERATION_POP] = " CMD.GLID_MAHJONG_OPERATION_POP 出牌"; //12811 出牌
CMD.GLID_MAHJONG_MJCARD_TING = (CMD.OGID_MSGBASE_ROOMMSGBASE + 12); cmdsorts[CMD.GLID_MAHJONG_MJCARD_TING] = " CMD.GLID_MAHJONG_MJCARD_TING 听牌"; //12812 听牌
CMD.GLID_MAHJONG_MJCARD_QIANGGANG = (CMD.OGID_MSGBASE_ROOMMSGBASE + 13); cmdsorts[CMD.GLID_MAHJONG_MJCARD_QIANGGANG] = " CMD.GLID_MAHJONG_MJCARD_QIANGGANG 抢杠"; //12813 抢杠

CMD.OGID_ROOMSVR_REQUPDATEMONEY = (CMD.OGID_MSGBASE_ROOMMSGBASE + 14); cmdsorts[CMD.OGID_ROOMSVR_REQUPDATEMONEY] = " CMD.OGID_ROOMSVR_REQUPDATEMONEY"; //12814

CMD.GLID_MAHJONG_OPERATION_HU = (CMD.OGID_MSGBASE_ROOMMSGBASE + 15); cmdsorts[CMD.GLID_MAHJONG_OPERATION_HU] = " CMD.GLID_MAHJONG_OPERATION_HU 胡牌类型"; //12815 胡牌类型
CMD.GLID_MAHJONG_OPERATION_TABLEINFO = (CMD.OGID_MSGBASE_ROOMMSGBASE + 16); cmdsorts[CMD.GLID_MAHJONG_OPERATION_TABLEINFO] = " CMD.GLID_MAHJONG_OPERATION_TABLEINFO 发送桌子信息"; //12816 发送桌子信息
CMD.GLID_MAHJONG_OPERATION_USERINFO = (CMD.OGID_MSGBASE_ROOMMSGBASE + 17); cmdsorts[CMD.GLID_MAHJONG_OPERATION_USERINFO] = " CMD.GLID_MAHJONG_OPERATION_USERINFO 发送玩家信息"; //12817 发送玩家信息
CMD.GLID_MAHJONG_OPERATION_READY = (CMD.OGID_MSGBASE_ROOMMSGBASE + 18); cmdsorts[CMD.GLID_MAHJONG_OPERATION_READY] = " CMD.GLID_MAHJONG_OPERATION_READY 准备"; //12818 准备
CMD.GLID_MAHJONG_SETTLEMENT = (CMD.OGID_MSGBASE_ROOMMSGBASE + 19); cmdsorts[CMD.GLID_MAHJONG_SETTLEMENT] = " CMD.GLID_MAHJONG_SETTLEMENT 最后的结算"; //12819 最后的结算
CMD.GLID_MAHJONG_OPERATION_MSG = (CMD.OGID_MSGBASE_ROOMMSGBASE + 20); cmdsorts[CMD.GLID_MAHJONG_OPERATION_MSG] = " CMD.GLID_MAHJONG_OPERATION_MSG 玩家进入 玩家信息"; //12820 玩家进入 玩家信息
CMD.GLID_MAHJONG_OPERATION_MOPAI = (CMD.OGID_MSGBASE_ROOMMSGBASE + 21); cmdsorts[CMD.GLID_MAHJONG_OPERATION_MOPAI] = " CMD.GLID_MAHJONG_OPERATION_MOPAI 摸牌"; //12821 摸牌
CMD.GLID_MAHJONG_OPERATION_JIESAN = (CMD.OGID_MSGBASE_ROOMMSGBASE + 22); cmdsorts[CMD.GLID_MAHJONG_OPERATION_JIESAN] = " CMD.GLID_MAHJONG_OPERATION_JIESAN 解散"; //12822 解散
CMD.GLID_MAHJONG_OPERATION_KILLP = (CMD.OGID_MSGBASE_ROOMMSGBASE + 23); cmdsorts[CMD.GLID_MAHJONG_OPERATION_KILLP] = " CMD.GLID_MAHJONG_OPERATION_KILLP 踢人"; //12823 踢人
CMD.GLID_MAHJONG_OPERATION_KOUPAI = (CMD.OGID_MSGBASE_ROOMMSGBASE + 24); cmdsorts[CMD.GLID_MAHJONG_OPERATION_KOUPAI] = " CMD.GLID_MAHJONG_OPERATION_KOUPAI 扣牌"; //12824 扣牌
CMD.GLID_MAHJONG_OPERATION_HUCARD = (CMD.OGID_MSGBASE_ROOMMSGBASE + 25); cmdsorts[CMD.GLID_MAHJONG_OPERATION_HUCARD] = " CMD.GLID_MAHJONG_OPERATION_HUCARD 表示听某张牌，可以胡哪几张"; //12825 表示听某张牌，可以胡哪几张
CMD.GLID_MAHJONG_OPERATION_USEREXIT = (CMD.OGID_MSGBASE_ROOMMSGBASE + 26); cmdsorts[CMD.GLID_MAHJONG_OPERATION_USEREXIT] = " CMD.GLID_MAHJONG_OPERATION_USEREXIT 用户自己退出"; //12826 用户自己退出
CMD.GLID_MAHJONG_OPERATION_OFFORONLE = (CMD.OGID_MSGBASE_ROOMMSGBASE + 27); cmdsorts[CMD.GLID_MAHJONG_OPERATION_OFFORONLE] = " CMD.GLID_MAHJONG_OPERATION_OFFORONLE 用户掉线或者掉线回来"; //12827 用户掉线或者掉线回来
CMD.GLID_MAHJONG_OPERATION_CHI = (CMD.OGID_MSGBASE_ROOMMSGBASE + 28); cmdsorts[CMD.GLID_MAHJONG_OPERATION_CHI] = " CMD.GLID_MAHJONG_OPERATION_CHI 吃牌"; //12828 吃牌
CMD.GLID_MAHJONG_OPERATION_BUHUA = (CMD.OGID_MSGBASE_ROOMMSGBASE + 29); cmdsorts[CMD.GLID_MAHJONG_OPERATION_BUHUA] = " CMD.GLID_MAHJONG_OPERATION_BUHUA 补花"; //12829 补花
CMD.GLID_MAHJONG_OPERATION_CHENGBAO = (CMD.OGID_MSGBASE_ROOMMSGBASE + 31); cmdsorts[CMD.GLID_MAHJONG_OPERATION_CHENGBAO] = " CMD.GLID_MAHJONG_OPERATION_CHENGBAO 承包"; //12831 承包

//游戏内的消息类型
CMD.OGID_MSG_BASE=0x3000; cmdsorts[CMD.OGID_MSG_BASE] = "CMD.OGID_MSG_BASE";
CMD.OGID_GAME_TURN = (CMD.OGID_MSG_BASE + 24); cmdsorts[CMD.OGID_GAME_TURN] = "当前玩家 CMD.OGID_GAME_TURN"; //12312当前玩家
CMD.OGID_GAME_USERLIST = (CMD.OGID_MSG_BASE + 25); cmdsorts[CMD.OGID_GAME_USERLIST] = " 房间内的玩家列表 CMD.OGID_GAME_USERLIST"; //12313 房间内的玩家列表
CMD.OGID_GAME_STATE = (CMD.OGID_MSG_BASE + 26); cmdsorts[CMD.OGID_GAME_STATE] = " 游戏内的状态信息 CMD.OGID_GAME_STATE"; //12314 游戏内的状态信息
CMD.OGID_GAME_MSG = (CMD.OGID_MSG_BASE + 27); cmdsorts[CMD.OGID_GAME_MSG] = " 有新玩家进入0;有玩家申请1;2是离开房间;3是玩家升级;4->heiha;5->领取救济金 CMD.OGID_GAME_MSG"; //12315 有新玩家进入0;有玩家申请1;2是离开房间;3是玩家升级;4->heiha;5->领取救济金
CMD.GLID_GAME_SLOTS = (CMD.OGID_MSG_BASE + 28); cmdsorts[CMD.GLID_GAME_SLOTS] = " Slots CMD.GLID_GAME_SLOTS"; //12316 Slots
CMD.GLID_GAME_SLOTSTART = (CMD.OGID_MSG_BASE + 29); cmdsorts[CMD.GLID_GAME_SLOTSTART] = " 下注达到条件开始Slots CMD.GLID_GAME_SLOTSTART"; //12317 下注达到条件开始Slots
CMD.GLID_GAME_BANK = (CMD.OGID_MSG_BASE + 30); cmdsorts[CMD.GLID_GAME_BANK] = " 银行操作 CMD.GLID_GAME_BANK"; //12318 银行操作
CMD.GLID_GAME_LOTT = (CMD.OGID_MSG_BASE + 31); cmdsorts[CMD.GLID_GAME_LOTT] = " 玩家获得彩金 CMD.GLID_GAME_LOTT"; //12319 玩家获得彩金
CMD.GLID_GAME_USER_GOLDS = (CMD.OGID_MSG_BASE + 32); cmdsorts[CMD.GLID_GAME_USER_GOLDS] = " 服务端玩家金币 CMD.GLID_GAME_USER_GOLDS"; //12320 服务端玩家金币
CMD.GLID_GAME_FAST_SIT = (CMD.OGID_MSG_BASE + 33); cmdsorts[CMD.GLID_GAME_FAST_SIT] = " 快速入座 CMD.GLID_GAME_FAST_SIT"; //12321 快速入座
CMD.GLID_GAME_USER_STATICS = (CMD.OGID_MSG_BASE + 34); cmdsorts[CMD.GLID_GAME_USER_STATICS] = " 本桌玩家的输赢 CMD.GLID_GAME_USER_STATICS"; //12322 本桌玩家的输赢
CMD.GLID_GAME_RECORD = (CMD.OGID_MSG_BASE + 36); cmdsorts[CMD.GLID_GAME_RECORD] = " 路子 CMD.GLID_GAME_RECORD"; //12324 路子
CMD.GLID_GAME_BUYSOMETHING = (CMD.OGID_MSG_BASE + 38); cmdsorts[CMD.GLID_GAME_BUYSOMETHING] = " 气球 CMD.GLID_GAME_BUYSOMETHING"; //12326


CMD.GLID_BASE_GAMEITEM = (CMD.OGID_MSG_BASE + 80); cmdsorts[CMD.GLID_BASE_GAMEITEM] = " CMD.GLID_BASE_GAMEITEM"; //12368
CMD.GLID_GAMEITEM_BOSS_INFO = (CMD.GLID_BASE_GAMEITEM + 1); cmdsorts[CMD.GLID_GAMEITEM_BOSS_INFO] = " 申请上庄 CMD.GLID_GAMEITEM_BOSS_INFO"; //12369 申请上庄
CMD.GLID_GAMEITEM_ROOM_INFO = (CMD.GLID_BASE_GAMEITEM + 2); cmdsorts[CMD.GLID_GAMEITEM_ROOM_INFO] = " 房间信息 CMD.GLID_GAMEITEM_ROOM_INFO"; //12370 房间信息
CMD.GLID_GAMEITEM_CONTINUE = (CMD.GLID_BASE_GAMEITEM + 3); cmdsorts[CMD.GLID_GAMEITEM_CONTINUE] = " CMD.GLID_GAMEITEM_CONTINUE"; //12371
CMD.GLID_GAMEITEM_KICKTOHALL = (CMD.GLID_BASE_GAMEITEM + 4); cmdsorts[CMD.GLID_GAMEITEM_KICKTOHALL] = "//踢回大厅 CMD.GLID_GAMEITEM_KICKTOHALL"; //12372//踢回大厅
CMD.GLID_GAMEITEM_PLACE = (CMD.GLID_BASE_GAMEITEM + 5); cmdsorts[CMD.GLID_GAMEITEM_PLACE] = " 坐下 CMD.GLID_GAMEITEM_PLACE"; //12373 坐下
CMD.GLID_GAMEITEM_BET = (CMD.GLID_BASE_GAMEITEM + 6); cmdsorts[CMD.GLID_GAMEITEM_BET] = " 下注 CMD.GLID_GAMEITEM_BET"; //12374 下注
CMD.GLID_GAMEITEM_STANDUP = (CMD.GLID_BASE_GAMEITEM + 7); cmdsorts[CMD.GLID_GAMEITEM_STANDUP] = " 离开座位 CMD.GLID_GAMEITEM_STANDUP"; //12375 离开座位
CMD.GLID_GAMEITEM_DEAL = (CMD.GLID_BASE_GAMEITEM + 8); cmdsorts[CMD.GLID_GAMEITEM_DEAL] = " 发牌 CMD.GLID_GAMEITEM_DEAL"; //12376 发牌
CMD.GLID_GAMEITEM_RESULT = (CMD.GLID_BASE_GAMEITEM + 9); cmdsorts[CMD.GLID_GAMEITEM_RESULT] = " 发送结果 CMD.GLID_GAMEITEM_RESULT"; //12377 发送结果
CMD.GLID_GAMEITEM_BETINFO = (CMD.GLID_BASE_GAMEITEM + 10); cmdsorts[CMD.GLID_GAMEITEM_BETINFO] = " 发送结果展示 CMD.GLID_GAMEITEM_BETINFO"; //12378 发送结果展示
CMD.GLID_GAMEITEM_PLAYER_SMILIE = (CMD.GLID_BASE_GAMEITEM + 11); cmdsorts[CMD.GLID_GAMEITEM_PLAYER_SMILIE] = " 发送表情 CMD.GLID_GAMEITEM_PLAYER_SMILIE"; //12379 发送表情
CMD.GLID_GAMEITEM_PLAYEREXP = (CMD.GLID_BASE_GAMEITEM + 12); cmdsorts[CMD.GLID_GAMEITEM_PLAYEREXP] = "经验值 CMD.GLID_GAMEITEM_PLAYEREXP"; //12380经验值
CMD.GLID_GAMEITEM_USE_PROP = (CMD.GLID_BASE_GAMEITEM + 13); cmdsorts[CMD.GLID_GAMEITEM_USE_PROP] = "玩家使用道具 CMD.GLID_GAMEITEM_USE_PROP"; //12381玩家使用道具
CMD.GLID_GAMEITEM_PLAYER_COIN = (CMD.GLID_BASE_GAMEITEM + 14); cmdsorts[CMD.GLID_GAMEITEM_PLAYER_COIN] = " 更新玩家金币 CMD.GLID_GAMEITEM_PLAYER_COIN"; //12382 更新玩家金币
CMD.GLID_GAMEITEM_PLAYER_CHIP = (CMD.GLID_BASE_GAMEITEM + 15); cmdsorts[CMD.GLID_GAMEITEM_PLAYER_CHIP] = " 更新玩家所下筹码 CMD.GLID_GAMEITEM_PLAYER_CHIP"; //12383 更新玩家所下筹码
CMD.GLID_GAMEITEM_FRIEND = (CMD.GLID_BASE_GAMEITEM + 16); cmdsorts[CMD.GLID_GAMEITEM_FRIEND] = "好友:0，加好友;1，删除好友 CMD.GLID_GAMEITEM_FRIEND"; //12384好友:0，加好友;1，删除好友
CMD.GLID_GAMEITEM_BONUS = (CMD.GLID_BASE_GAMEITEM + 17); cmdsorts[CMD.GLID_GAMEITEM_BONUS] = "玩家掉落宝石或者筹码 CMD.GLID_GAMEITEM_BONUS"; //12385玩家掉落宝石或者筹码
CMD.GLID_GAMEITEM_BUY_SMILE = (CMD.GLID_BASE_GAMEITEM + 18); cmdsorts[CMD.GLID_GAMEITEM_BUY_SMILE] = "玩家购买表情包 CMD.GLID_GAMEITEM_BUY_SMILE"; //12386玩家购买表情包
CMD.GLID_GAMEITEM_GIVECARD = (CMD.GLID_BASE_GAMEITEM + 19); cmdsorts[CMD.GLID_GAMEITEM_GIVECARD] = " 要牌状态 CMD.GLID_GAMEITEM_GIVECARD"; //12387 要牌状态
CMD.GLID_GAMEITEM_STARTGAME = (CMD.GLID_BASE_GAMEITEM + 20); cmdsorts[CMD.GLID_GAMEITEM_STARTGAME] = "登陆重连发送信息 CMD.GLID_GAMEITEM_STARTGAME"; //12388登陆重连发送信息
CMD.GLID_GAMEITEM_ISBUYSAFE = (CMD.GLID_BASE_GAMEITEM + 21); cmdsorts[CMD.GLID_GAMEITEM_ISBUYSAFE] = " 询问玩家是否买保险 CMD.GLID_GAMEITEM_ISBUYSAFE"; //12389 询问玩家是否买保险
CMD.GLID_GAMEITEM_BUYINSURANCE = (CMD.GLID_BASE_GAMEITEM + 22); cmdsorts[CMD.GLID_GAMEITEM_BUYINSURANCE] = " 买保险 CMD.GLID_GAMEITEM_BUYINSURANCE"; //12390 买保险
CMD.GLID_GAMEITEM_DOUBLE = (CMD.GLID_BASE_GAMEITEM + 23); cmdsorts[CMD.GLID_GAMEITEM_DOUBLE] = " 加倍 CMD.GLID_GAMEITEM_DOUBLE"; //12391 加倍
CMD.GLID_GAMEITEM_STOPCARD = (CMD.GLID_BASE_GAMEITEM + 24); cmdsorts[CMD.GLID_GAMEITEM_STOPCARD] = " 停牌 CMD.GLID_GAMEITEM_STOPCARD"; //12392 停牌
CMD.GLID_GAMEITEM_PARTCARD = (CMD.GLID_BASE_GAMEITEM + 25); cmdsorts[CMD.GLID_GAMEITEM_PARTCARD] = " 分牌 CMD.GLID_GAMEITEM_PARTCARD"; //12393 分牌
CMD.GLID_GAMEITEM_SCORE = (CMD.GLID_BASE_GAMEITEM + 26); cmdsorts[CMD.GLID_GAMEITEM_SCORE] = " 算分 CMD.GLID_GAMEITEM_SCORE"; //12394 算分
CMD.GLID_GAMEITEM_NEWCARD = (CMD.GLID_BASE_GAMEITEM + 27); cmdsorts[CMD.GLID_GAMEITEM_NEWCARD] = " 要牌 CMD.GLID_GAMEITEM_NEWCARD"; //12395 要牌
CMD.GLID_GAMEITEM_CLIENTFUN = (CMD.GLID_BASE_GAMEITEM + 28); cmdsorts[CMD.GLID_GAMEITEM_CLIENTFUN] = "客户端可操作功能 CMD.GLID_GAMEITEM_CLIENTFUN"; //12396客户端可操作功能
CMD.GLID_GAMEITEM_ALLPROP = (CMD.GLID_BASE_GAMEITEM + 29); cmdsorts[CMD.GLID_GAMEITEM_ALLPROP] = "群发道具 CMD.GLID_GAMEITEM_ALLPROP"; //12397群发道具
CMD.GLID_GAMEITEM_BOSSCARDINFO = (CMD.GLID_BASE_GAMEITEM + 30); cmdsorts[CMD.GLID_GAMEITEM_BOSSCARDINFO] = "庄家牌 CMD.GLID_GAMEITEM_BOSSCARDINFO"; //12398庄家牌
CMD.GLID_GAMEITEM_LOTTERYAWARD = (CMD.GLID_BASE_GAMEITEM + 31); cmdsorts[CMD.GLID_GAMEITEM_LOTTERYAWARD] = "彩票奖励 CMD.GLID_GAMEITEM_LOTTERYAWARD"; //12399彩票奖励
CMD.GLID_GAMEITEM_BUYLOTTERY = (CMD.GLID_BASE_GAMEITEM + 32); cmdsorts[CMD.GLID_GAMEITEM_BUYLOTTERY] = "购买大乐透 CMD.GLID_GAMEITEM_BUYLOTTERY"; //12400购买大乐透
CMD.GLID_GAMEITEM_LOTTERYRESULT = (CMD.GLID_BASE_GAMEITEM + 33); cmdsorts[CMD.GLID_GAMEITEM_LOTTERYRESULT] = "彩金每轮结算 CMD.GLID_GAMEITEM_LOTTERYRESULT"; //12401彩金每轮结算
CMD.GLID_GAMEITEM_LEAVE = (CMD.GLID_BASE_GAMEITEM + 34); cmdsorts[CMD.GLID_GAMEITEM_LEAVE] = "暂离 CMD.GLID_GAMEITEM_LEAVE"; //12402暂离
CMD.GLID_GAMEITEM_BETOVER = (CMD.GLID_BASE_GAMEITEM + 35); cmdsorts[CMD.GLID_GAMEITEM_BETOVER] = "下注结束 CMD.GLID_GAMEITEM_BETOVER"; //12403下注结束
CMD.GLID_GAMEITEM_FOLD = (CMD.GLID_BASE_GAMEITEM + 36); cmdsorts[CMD.GLID_GAMEITEM_FOLD] = " 投降 CMD.GLID_GAMEITEM_FOLD"; //12404 投降
CMD.GLID_GAMEITEM_DEALDOUBLE = (CMD.GLID_BASE_GAMEITEM + 37); cmdsorts[CMD.GLID_GAMEITEM_DEALDOUBLE] = " 结算前发加倍门的第三张牌给前端 CMD.GLID_GAMEITEM_DEALDOUBLE"; //12405 结算前发加倍门的第三张牌给前端
CMD.GLID_GAMEITEM_REBET = (CMD.GLID_BASE_GAMEITEM + 38); cmdsorts[CMD.GLID_GAMEITEM_REBET] = " 重复下注 CMD.GLID_GAMEITEM_REBET"; //12406 重复下注
CMD.GLID_GAMEITEM_PAIR_RESULT = (CMD.GLID_BASE_GAMEITEM + 39); cmdsorts[CMD.GLID_GAMEITEM_PAIR_RESULT] = " 发送对子结果 CMD.GLID_GAMEITEM_PAIR_RESULT"; //12407 发送对子结果
CMD.GLID_GAMEITEM_INSURANCE_RESULT = (CMD.GLID_BASE_GAMEITEM + 40); cmdsorts[CMD.GLID_GAMEITEM_INSURANCE_RESULT] = " 发送保险结算结果 CMD.GLID_GAMEITEM_INSURANCE_RESULT"; //12408 发送保险结算结果
CMD.GLID_GAMEITEM_FOLD_RESULT = (CMD.GLID_BASE_GAMEITEM + 41); cmdsorts[CMD.GLID_GAMEITEM_FOLD_RESULT] = " 投降结算结果 CMD.GLID_GAMEITEM_FOLD_RESULT"; //12409 投降结算结果
CMD.GLID_GAMEITEM_CAN_BET = (CMD.GLID_BASE_GAMEITEM + 42); cmdsorts[CMD.GLID_GAMEITEM_CAN_BET] = " 区域限制 CMD.GLID_GAMEITEM_CAN_BET"; //12410  区域限制
CMD.GLID_GAMEITEM_CHAT = (CMD.GLID_BASE_GAMEITEM + 43); cmdsorts[CMD.GLID_GAMEITEM_CHAT] = " 游戏聊天 CMD.GLID_GAMEITEM_CHAT"; //12411 游戏聊天
CMD.GLID_GAMEITEM_JOB = (CMD.GLID_BASE_GAMEITEM + 44); cmdsorts[CMD.GLID_GAMEITEM_JOB] = " 包桌 CMD.GLID_GAMEITEM_JOB"; //12412 包桌
CMD.GLID_GAMEITEM_JOB_CANCEL = (CMD.GLID_BASE_GAMEITEM + 45); cmdsorts[CMD.GLID_GAMEITEM_JOB_CANCEL] = " 取消包桌 CMD.GLID_GAMEITEM_JOB_CANCEL"; //12413 取消包桌
CMD.GLID_GAMEITEM_JOB_DRAW = (CMD.GLID_BASE_GAMEITEM + 46); cmdsorts[CMD.GLID_GAMEITEM_JOB_DRAW] = " 包桌取钱 CMD.GLID_GAMEITEM_JOB_DRAW"; //12414 包桌取钱
CMD.GLID_GAMEITEM_JOB_DEPOSIT = (CMD.GLID_BASE_GAMEITEM + 47); cmdsorts[CMD.GLID_GAMEITEM_JOB_DEPOSIT] = " 包桌存钱 CMD.GLID_GAMEITEM_JOB_DEPOSIT"; //12415 包桌存钱
CMD.GLID_GAMEITEM_JOB_CHANGE = (CMD.GLID_BASE_GAMEITEM + 48); cmdsorts[CMD.GLID_GAMEITEM_JOB_CHANGE] = " 包桌 承包人分数变化 CMD.GLID_GAMEITEM_JOB_CHANGE"; //12416 包桌 承包人分数变化
CMD.GLID_GAMEITEM_CHIPS = (CMD.GLID_BASE_GAMEITEM + 49); cmdsorts[CMD.GLID_GAMEITEM_CHIPS] = " 带人筹码 CMD.GLID_GAMEITEM_CHIPS"; //12417 带人筹码
CMD.GLID_GAMEITEM_ARRANGE = (CMD.GLID_BASE_GAMEITEM + 50); cmdsorts[CMD.GLID_GAMEITEM_ARRANGE] = " 扣除大小盲注(发送给前端大小盲注情况) CMD.GLID_GAMEITEM_ARRANGE"; //12418 扣除大小盲注(发送给前端大小盲注情况);
CMD.GLID_GAMEITEM_SHOW_CARDS = (CMD.GLID_BASE_GAMEITEM + 51); cmdsorts[CMD.GLID_GAMEITEM_SHOW_CARDS] = " 亮手牌 CMD.GLID_GAMEITEM_SHOW_CARDS"; //12419 亮手牌
CMD.GLID_GAMEITEM_SIDE_POT = (CMD.GLID_BASE_GAMEITEM + 52); cmdsorts[CMD.GLID_GAMEITEM_SIDE_POT] = " 边池 CMD.GLID_GAMEITEM_SIDE_POT"; //12420 边池
CMD.GLID_GAMEITEM_SHARK = (CMD.GLID_BASE_GAMEITEM + 55); cmdsorts[CMD.GLID_GAMEITEM_SHARK] = " 德州 鲨鱼分 CMD.GLID_GAMEITEM_SHARK"; //12423 德州 鲨鱼分
CMD.GLID_TEXAS_CANCEL_TABLE = (CMD.GLID_BASE_GAMEITEM + 56); cmdsorts[CMD.GLID_TEXAS_CANCEL_TABLE] = " 德州 USER解散桌子 CMD.GLID_TEXAS_CANCEL_TABLE"; //12424 德州 USER解散桌子
CMD.GLID_GAMEITEM_CREATE_END = (CMD.GLID_BASE_GAMEITEM + 67); cmdsorts[CMD.GLID_GAMEITEM_CREATE_END] = " 德州 解散桌子 show 成绩 CMD.GLID_GAMEITEM_CREATE_END"; //12435 德州 解散桌子 show 成绩

CMD.GLID_GAMEITEM_SAVING = (CMD.GLID_BASE_GAMEITEM + 54); cmdsorts[CMD.GLID_GAMEITEM_SAVING] = cmdsorts[CMD.GLID_GAMEITEM_SAVING] = " 存钱罐 CMD.GLID_GAMEITEM_SAVING"; //12422 存钱罐

CMD.GLID_GAMEITEM_FIVE_BUNOS = (CMD.GLID_BASE_GAMEITEM + 61); cmdsorts[CMD.GLID_GAMEITEM_FIVE_BUNOS] = cmdsorts[CMD.GLID_GAMEITEM_FIVE_BUNOS] = " 大于5人WIN 奖励 CMD.GLID_GAMEITEM_FIVE_BUNOS"; //12429 大于5人WIN 奖励
CMD.GLID_GAMEITEM_RESET = (CMD.GLID_BASE_GAMEITEM + 62); cmdsorts[CMD.GLID_GAMEITEM_RESET] = cmdsorts[CMD.GLID_GAMEITEM_RESET] = "CMD.GLID_GAMEITEM_RESET"; //12430
CMD.GLID_GAMEITEM_SHOW_CARD = (CMD.GLID_BASE_GAMEITEM + 63); cmdsorts[CMD.GLID_GAMEITEM_SHOW_CARD] = cmdsorts[CMD.GLID_GAMEITEM_SHOW_CARD] = " CMD.GLID_GAMEITEM_SHOW_CARD"; //12431
CMD.GLID_GAMEITEM_DROP_STARO = (CMD.GLID_BASE_GAMEITEM + 64); cmdsorts[CMD.GLID_GAMEITEM_DROP_STARO] = cmdsorts[CMD.GLID_GAMEITEM_DROP_STARO] = " 星币掉落 CMD.GLID_GAMEITEM_DROP_STARO"; //12432 星币掉落
